---
# tasks file for alb-ingress-controller

- name: Helm chart exists
  synchronize:
    src: alb-ingress-controller/
    dest: "{{alb_ingress_controller_helm_chart_path}}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes

- name: Install the alb-ingress-controller
  command:
    argv:
      - helm
      - upgrade
      - --install
      - --namespace=kube-system
      - --set=clusterName={{kubectl_eks_cluster_name}}
      - --set=image.tag={{alb_ingress_controller_tag}}
      - ingress-controller
      - "{{alb_ingress_controller_helm_chart_path}}"
  environment: "{{ kubectl_env }}"
