---
# basic configuration for the node_exporter installation.
prometheus_node_exporter_version: "0.15.2"
prometheus_node_exporter_root_path: "/opt/prometheus/node_exporter"

# configuration determining how the node exporter communicates with prometheus
# servers.
prometheus_node_exporter_web_listen_address: ":9111"
prometheus_node_exporter_web_telemetry_path: "/metrics"

# configure collectors exposed by the node exporter.
prometheus_node_exporter_enabled_collectors:
    - ntp
prometheus_node_exporter_disabled_collectors:
    - arp
    - bcache
    - bonding
    - conntrack
    - edac
    - entropy
    - ipvs
    - netdev
    - wifi
    - xfs
    - zfs

prometheus_node_exporter_filesystem_ignored_mount_points: "^/(sys|proc|dev|host|etc|var/lib/docker/containers|var/lib/docker/overlay2|run/docker/netns|var/lib/docker/aufs)($$|/)"

# internal installation variables
prometheus_node_exporter_release_name: "node_exporter-{{prometheus_node_exporter_version}}.linux-amd64"
prometheus_node_exporter_archive_name: "{{prometheus_node_exporter_release_name}}.tar.gz"
prometheus_node_exporter_bin: "{{prometheus_node_exporter_root_path}}/node_exporter"
prometheus_node_exporter_runner: "{{prometheus_node_exporter_root_path}}/node_exporter.sh"
prometheus_node_exporter_release_path: "{{prometheus_node_exporter_root_path}}/{{prometheus_node_exporter_release_name}}"
prometheus_node_exporter_release_bin: "{{prometheus_node_exporter_release_path}}/node_exporter"
prometheus_node_exporter_archive: "{{prometheus_node_exporter_root_path}}/{{prometheus_node_exporter_archive_name}}"
prometheus_node_exporter_systemd_service: node_exporter.service

# release archive source information
prometheus_node_exporter_s3_bucket: luther-common-ln-common-static-s3-b5oc
prometheus_node_exporter_s3_key: "prometheus/node_exporter/{{prometheus_node_exporter_archive_name}}"
prometheus_node_exporter_aws_access_key: "{{lookup('env', 'AWS_ACCESS_KEY_ID')}}"
prometheus_node_exporter_aws_secret_key: "{{lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"
