{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "oracle.fullname" . }}
  labels:
    {{- include "oracle.labels" . | nindent 4 }}
rules:
{{- with .Values.rbac.permissions }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
