apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle.fullname" . }}
  labels:
    {{- include "oracle.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.metrics | quote }}
    alb.ingress.kubernetes.io/healthcheck-path: '/v1/{{ .Values.app.name }}/health_check{{ if .Values.httpOnlyProbe }}?http_only=true{{ end }}'
    alb.ingress.kubernetes.io/healthcheck-port: "traffic-port"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{ include "oracle.labels.match" . | nindent 4 }}
