---
- name: Root directory exists
  file: path={{prometheus_node_exporter_root_path}} state=directory owner=root group=root recurse=yes
  tags:
      - prometheus

- name: Release archive exists
  aws_s3:
      mode: get
      overwrite: different
      dest: "{{prometheus_node_exporter_archive}}"
      region: eu-west-2
      bucket: "{{prometheus_node_exporter_s3_bucket}}"
      object: "{{prometheus_node_exporter_s3_key}}"
      ignore_nonexistent_bucket: true
  tags:
      - prometheus

- name: Release has been unarchived
  unarchive: dest={{prometheus_node_exporter_root_path}} src={{prometheus_node_exporter_archive}} remote_src=yes owner=root group=root
  tags:
      - prometheus

# NOTE:  node_exporter should not run as root.
- name: Executable permissions are set correctly
  file: path={{prometheus_node_exporter_release_bin}} owner=root group=root mode=0755
  tags:
      - prometheus

- name: Executable symlink exists
  file: dest={{prometheus_node_exporter_bin}} state=link src={{prometheus_node_exporter_release_bin}} owner=root group=root mode=0755
  tags:
      - prometheus
  notify:
      - node_exporter enable
      - node_exporter restart

- name: Wrapper script exists
  template: dest={{prometheus_node_exporter_runner}} src=node_exporter.sh.j2 owner=root group=root mode=0755
  tags:
      - prometheus
  notify:
      - node_exporter enable
      - node_exporter restart

- name: Systemd unit exists
  template: dest=/etc/systemd/system/{{prometheus_node_exporter_systemd_service}} src=node_exporter.service.j2
  tags:
      - prometheus
  notify:
      - node_exporter enable
      - node_exporter restart

- name: Service is started
  command: /bin/true
  tags:
      - prometheus
  notify:
      - node_exporter enable
      - node_exporter start

- name: Process handlers
  meta: flush_handlers
  tags:
      - prometheus
