---
# tasks file for k8s_pv_data

- name: retrieve PVs
  kubernetes.core.k8s_info:
    api_version: v1
    kind: PersistentVolume
    label_selectors: "{{k8s_pv_data_selectors}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"
  register: vol_list

- name: set k8s_pv_data_replica_azs
  set_fact:
    k8s_pv_data_replica_azs: "{{ vol_list.resources | k8s_label_to_label_map('replica-index', 'int', k8s_pv_data_zone_label) }}"
