---
# tasks file for k8s_pv_data

- name: retrieve PVs
  kubernetes.core.k8s_info:
    api_version: v1
    kind: PersistentVolume
    label_selectors: "{{k8s_pv_data_selectors}}"
  environment: "{{ kubectl_env }}"
  register: vol_list

- name: set k8s_pv_data_replica_azs
  set_fact:
    k8s_pv_data_replica_azs: "{{ vol_list.resources | k8s_label_to_label_map('replica-index', 'int', k8s_pv_data_zone_label) }}"
