apiVersion: v1
kind: Service
metadata:
  name: {{ include "supergateway.fullname" . }}
  labels: {{- include "supergateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
  selector: {{- include "supergateway.labels.match" . | nindent 4 }}
