{
 "title": "Shiro Gateway",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Simulation duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.97, sum(rate(fabricclient_tx_sim_dur_ms_bucket[5m]) or rate(fabricgateway_tx_sim_dur_ms_bucket[5m])) by (le))",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Commit duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.97, sum(rate(fabricclient_tx_commit_dur_ms_bucket[5m]) or rate(fabricgateway_tx_commit_dur_ms_bucket[5m])) by (le))",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Tx calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(fabricclient_tx_total[5m]) or rate(fabricgateway_tx_total[5m])) * 60",
     "legendFormat": "calls"
    }
   ]
  },
  {
   "title": "Successful API Calls",
   "type": "graph",
   "description": "How many calls is the api serving successfully?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Calls/Minute" }
   ],
   "targets": [
    {
     "expr": "sum (increase(grpc_client_handled_total{grpc_code=\"OK\",job!=\"kubernetes-apiservers\"}[1m]))",
     "legendFormat": "calls"
    }
   ]
  },
  {
   "title": "Simulate errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (group,code) (rate(fabricclient_tx_sim_err_total[5m]) or rate(fabricgateway_tx_sim_err_total[5m])) * 60",
     "legendFormat": "{{group}}/{{code}}"
    }
   ]
  },
  {
   "title": "Commit errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(fabricclient_tx_commit_err_total[5m]) or rate(fabricgateway_tx_commit_err_total[5m])) * 60",
     "legendFormat": "{{group}}/{{code}}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(fabricclient_tx_retry_total[5m]) or rate(fabricgateway_tx_retry_total[5m])) * 60",
     "legendFormat": "retries"
    }
   ]
  },
  {
   "title": "Failed API Calls",
   "type": "graph",
   "description": "How many API calls are failing?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Failures/Minute over 2m" }
   ],
   "targets": [
    {
     "expr": "sum (increase(grpc_client_handled_total{grpc_code!=\"OK\",job!=\"kubernetes-apiservers\"}[1m]))",
     "legendFormat": "calls"
    }
   ]
  },
  {
   "title": "Simulations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(fabricclient_tx_sim_total[5m]) or rate(fabricgateway_tx_sim_total[5m])) * 60",
     "legendFormat": "simulations"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(fabricclient_tx_commit_total[5m]) or rate(fabricgateway_tx_commit_total[5m])) * 60",
     "legendFormat": "commits"
    }
   ]
  }
 ]
}