---
- name: Check kubectl_eks_cluster_name
  fail:
    msg: "A value must be provided for kubectl_eks_cluster_name"
  when: not kubectl_eks_cluster_name

- name: Print desired kubectl version
  debug:
    var: kubectl_version

- name: Install apt packages
  apt:
    update_cache: yes
    cache_valid_time: 36400
    install_recommends: no
    pkg:
      - jq
      - python3-pip
      - python3-venv

- name: Install python modules
  block:
    - name: Create temporary requirements file
      ansible.builtin.tempfile:
        state: file
        suffix: .txt
        prefix: requirements_
      register: requirements_tempfile
    - name: Copy pip requirements.txt
      copy:
        src: "requirements.python{{ python_minor }}.txt"
        dest: "{{ requirements_tempfile.path }}"
        owner: root
        group: root
        mode: "0644"
      vars:
        python_minor: "{{ ansible_python_version | splitext | first }}"
    - name: Ensure python modules are installed
      pip:
        requirements: "{{ requirements_tempfile.path }}"
        virtualenv: "{{ bastion_init_virtualenv }}"
        virtualenv_command: "{{ ansible_python.executable }} -m venv"
  always:
    - name: Remove temporary requirements file
      file:
        path: "{{ requirements_tempfile.path }}"
        state: absent

- name: Print AWS CLI desired version
  debug:
    var: aws_cli_version_desired

- name: Check AWS CLI version
  command:
    cmd: aws --version
  register: aws_cli_version_installed
  changed_when: no
  failed_when: no

- name: Set AWS CLI installed fact
  set_fact:
    aws_cli_installed: "{{ 'aws-cli/' + aws_cli_version_desired in aws_cli_version_installed.stdout }}"

- name: Copy AWS CLI public key to the bastion
  copy:
    src: aws-cli-pkg-key.asc
    dest: /tmp/aws-cli-pkg-key.asc
  when: not aws_cli_installed

- name: Import AWS CLI public key
  command:
    cmd: gpg --import /tmp/aws-cli-pkg-key.asc
  when: not aws_cli_installed

- name: Download the specific AWS CLI v2 installer
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ aws_cli_version_desired }}.zip"
    dest: "/tmp/awscliv2.zip"
  when: not aws_cli_installed

- name: Download AWS CLI v2 signature file
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ aws_cli_version_desired }}.zip.sig"
    dest: "/tmp/awscliv2.sig"
  when: not aws_cli_installed

- name: Verify the signature of the AWS CLI v2 installer
  command:
    cmd: gpg --verify /tmp/awscliv2.sig /tmp/awscliv2.zip
  when: not aws_cli_installed

- name: Install unzip package
  become: true
  package:
    name: unzip
    state: present
  when: not aws_cli_installed

- name: Unzip the AWS CLI v2 installer
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes
  when: not aws_cli_installed

- name: Run the AWS CLI v2 installer
  command: "/tmp/aws/install --update"
  when: not aws_cli_installed

- name: Cleanup temporary files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/awscli-exe-linux-x86_64-{{ aws_cli_version_desired }}.zip"
    - "/tmp/awscli-exe-linux-x86_64-{{ aws_cli_version_desired }}.zip.sig"
    - "/tmp/aws-cli-pkg-key.asc"
    - "/tmp/aws"
  when: not aws_cli_installed

- import_role:
    name: kubectl
  vars:
    kubectl_configure: yes
    kubectl_python_interpreter: "{{ bastion_init_virtualenv }}/bin/python"

- name: Set kubeconfig.yaml permissions
  file:
    path: "{{kubectl_config_path}}"
    owner: ubuntu
    group: ubuntu
    mode: "0600"

- name: Install kubectl shell helpers
  copy:
    src: kubectl.sh
    dest: /etc/profile.d/kubectl.sh

- name: Install luther_vars.sh
  template:
    src: luther_vars.sh.j2
    dest: /etc/luther_vars.sh
    mode: 0644

- name: Install .bashrc
  copy:
    src: bashrc
    dest: "{{ item.dir }}/.bashrc"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0644
  loop:
    - dir: "/etc/skel"
      owner: root
      group: root
    - dir: "/home/ubuntu"
      owner: ubuntu
      group: ubuntu
    - dir: "/root"
      owner: root
      group: root

- name: check terminfo for xterm-24bit
  command:
    cmd: infocmp xterm-24bit
  register: infocmp
  failed_when: infocmp.rc > 1
  changed_when: no

- name: Install terminfo for xterm-24bit
  when: infocmp.rc == 1
  block:
    - name: Create temporary terminfo file
      ansible.builtin.tempfile:
        state: file
        suffix: .terminfo
        prefix: xterm-24bit_
      register: xterm24_tempfile
    - name: Copy xterm-24bit terminfo
      copy:
        src: xterm-24bit.terminfo
        dest: "{{ xterm24_tempfile.path }}"
        owner: root
        group: root
        mode: "0644"
    - name: Compile xterm-24bit terminfo
      command:
        argv:
          - tic
          - -x
          - -o
          - /etc/terminfo
          - "{{ xterm24_tempfile.path }}"
  always:
    - name: Remove temporary terminfo file
      file:
        path: "{{ xterm24_tempfile.path }}"
        state: absent

- name: Configure unattended upgrades
  copy:
    src: 51unattended-upgrades-custom
    dest: /etc/apt/apt.conf.d/51unattended-upgrades-custom
    owner: root
    group: root
    mode: "0644"

- name: install Prometheus Node Exporter
  include_role:
    name: prometheus.prometheus.node_exporter
