---
- name: Check kubectl_eks_cluster_name
  fail:
    msg: "A value must be provided for kubectl_eks_cluster_name"
  when: not kubectl_eks_cluster_name

- name: Print desired kubectl version
  debug:
    var: kubectl_version

- name: Update the APT cache
  apt:
    update_cache: yes
    cache_valid_time: 36400

- name: jq is installed
  apt:
    name: jq
    state: present

- name: Pip is installed
  apt:
    name: python3-pip
    state: present

- name: Ensure python modules are installed
  pip:
    name:
      - awscli==1.22.50
      - boto==2.49.0
      - boto3==1.20
      - botocore==1.23.50
      - kubernetes==21.7.0
      - openshift==0.13.1

- name: Configure kubectl for EKS
  shell: "{{kubectl_shell_prefix}} aws --region {{kubectl_eks_region|quote}} eks update-kubeconfig --name {{kubectl_eks_cluster_name|quote}}"

- name: Install kubectl shell helpers
  copy:
    src: kubectl.sh
    dest: /etc/profile.d/kubectl.sh

- name: Install luther_vars.sh
  template:
    src: luther_vars.sh.j2
    dest: /etc/luther_vars.sh
    mode: 0644

- name: Install .bashrc
  copy:
    src: bashrc
    dest: "{{ item.dir }}/.bashrc"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0644
  loop:
    - dir: '/etc/skel'
      owner: root
      group: root
    - dir: '/home/ubuntu'
      owner: ubuntu
      group: ubuntu
    - dir: '/root'
      owner: root
      group: root
