{{- $fullName := include "ingress.fullname" . -}}
{{- $albAttrs := include "ingress.albAttributes" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "ingress.labels" . | indent 4 }}
  annotations:
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-Ext-2018-06"
    alb.ingress.kubernetes.io/scheme: {{ .Values.loadBalancer.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.loadBalancer.targetType | quote }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.loadBalancer.backendProtocol | quote }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.loadBalancer.certificateARN | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/tags: Project={{ .Values.global.partOf }},Environment={{ .Values.global.projectEnv }},Organization={{ .Values.global.orgName }},Component=app,Resource=alb
    alb.ingress.kubernetes.io/load-balancer-attributes: {{ $albAttrs | quote }}
{{ if .Values.annotations }}
{{ range $k, $v := .Values.annotations }}
    {{ $k }}: {{- if kindIs "string" $v }} {{ $v | quote }} {{- else }} {{ toJson $v | quote }} {{- end }}
{{ end }}
{{ end }}
{{- if and .Values.externalDNS (ne .Values.matchHost "") }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.matchHost | quote }}
{{- end }}
spec:
  ingressClassName:  {{ .Values.loadBalancer.class }}
  rules:
    - host: {{ .Values.matchHost | quote }}
      http:
        paths:
        {{- range .Values.serviceRoutes }}
          - pathType: Prefix
            path: {{ .path }}
            backend:
              service:
                name: {{ list $releaseName .service | include "ingress.service-name" }}
                port:
                  number: {{ .port }}
        {{- end }}
