{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pushprox.serviceAccountName" . }}
  labels:
{{ include "pushprox.labels" . | indent 4 }}
{{- end -}}
