---
# tasks file for kubectl

- name: kubectl setup
  include_tasks: setup.yml
  when:
    - not kubectl_setup or kubectl_upgrade
    - not kubectl_configured

- name: kubectl env setup
  include_tasks: env.yml
  when: not kubectl_configured
