---
- name: Check kubectl_version
  fail:
    msg: "A value must be provided for kubectl_version"
  when: not kubectl_version

- name: Check installed kubectl version
  command:
    argv:
      - snap
      - info
      - kubectl
  register: kubectl_snap_info_str
  changed_when: no
  check_mode: no
  when: kubectl_upgrade | bool

- name: Check whether upgrade is required
  set_fact:
    kubectl_needs_upgrade: "{{ kubectl_installed_channel != kubectl_channel }}"
    kubectl_installed: "{{ kubectl_snap_info.tracking is defined }}"
    kubectl_channel: "{{ kubectl_channel }}"
  vars:
    kubectl_channel: "{{ kubectl_version }}/stable"
    kubectl_snap_info: "{{ kubectl_snap_info_str.stdout | from_yaml }}"
    kubectl_installed_channel: "{{ kubectl_snap_info.tracking | default('') }}"
  when: kubectl_upgrade | bool

- name: Install the kubectl snap package
  community.general.snap:
    name: kubectl
    channel: "{{kubectl_channel}}"
    classic: yes
    state: present
  when:
    - kubectl_upgrade | bool
    - not kubectl_installed

- name: Upgrade kubectl snap package
  command:
    argv:
      - snap
      - refresh
      - "--channel={{kubectl_channel}}"
      - kubectl
  when:
    - kubectl_upgrade | bool
    - kubectl_installed
    - kubectl_needs_upgrade

- name: Complete kubectl setup
  set_fact:
    kubectl_setup: yes
