---
- name: Check kubectl_version var
  fail:
    msg: "A value must be provided for kubectl_version"
  when: not kubectl_version

- name: Add an apt signing key for Kubernetes
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when:
    - not kubectl_setup

- name: Adding apt repository for Kubernetes
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
  when:
    - not kubectl_setup

- name: Install kubectl binaries
  ansible.builtin.apt:
    name:
      - kubectl={{kubectl_version}}*
    state: present
    update_cache: yes

- name: Complete kubectl setup
  set_fact:
    kubectl_setup: yes
