---
- name: Check kubectl_version var
  fail:
    msg: "A value must be provided for kubectl_version"
  when: not kubectl_version

- name: Add an apt signing key for Kubernetes
  ansible.builtin.apt_key:
    # the signing key is shared across versions
    url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
    id: DE15B14486CD377B9E876E1A234654DA9A296436
    state: present
  when:
    - not kubectl_setup

- name: Add an apt signing key for Hashicorp
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  when:
    - not kubectl_setup

- name: Remove old Kubernetes repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: absent
    filename: kubernetes.list
  when:
    - not kubectl_setup

- name: Adding apt repository for Kubernetes
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=DE15B14486CD377B9E876E1A234654DA9A296436] https://pkgs.k8s.io/core:/stable:/v{{kubectl_version}}/deb/ /"
    state: present
    filename: kubernetes
  when:
    - not kubectl_setup

- name: Install kubectl binaries
  ansible.builtin.apt:
    name:
      - kubectl={{kubectl_version}}*
    state: present
    update_cache: yes

- name: Complete kubectl setup
  set_fact:
    kubectl_setup: yes
