apiVersion: v1
kind: Service
metadata:
  name: {{ include "lutherauth.fullname" . }}
  labels:
    {{- include "lutherauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ include "lutherauth.name" . }}
  selector:
    {{- include "lutherauth.labels" . | nindent 4 }}
