apiVersion: v1
kind: Service
metadata:
  name: {{ include "lutherauth.fullname" . }}
  labels:
    {{- include "lutherauth.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/v1/auth/.well-known/jwks.json"
    alb.ingress.kubernetes.io/healthcheck-port: "traffic-port"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ include "lutherauth.name" . }}
  selector:
    {{- include "lutherauth.labels" . | nindent 4 }}
