---
# tasks file for k8s_fabric_cli

- name: K8s namespace exists
  k8s:
    name: "{{k8s_fabric_cli_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
  environment: "{{ kubectl_env }}"

- name: Set crypto-config facts
  set_fact:
    k8s_fabric_cli_crypto_config_secret_name: fabric-crypto-config
  when: k8s_fabric_cli_crypto_config

- name: Fabric crypto-config secrets exists
  k8s:
    namespace: "{{k8s_fabric_cli_namespace}}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{crypto_config_secret}}"
      type: Opaque
      data:
        crypto-config.zip: "{{k8s_fabric_cli_crypto_config}}"
  no_log: True
  environment: "{{ kubectl_env }}"
  vars:
    crypto_config_secret: "{{k8s_fabric_cli_crypto_config_secret_name}}"
  when: k8s_fabric_cli_crypto_config

- name: Set channel-artifacts facts
  set_fact:
    k8s_fabric_cli_channel_artifacts_configmap_name: fabric-channel-artifacts
  when: k8s_fabric_cli_channel_artifacts

- name: Fabric channel-artifacts configmap exists
  k8s:
    namespace: "{{k8s_fabric_cli_namespace}}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{channel_artifacts_configmap}}"
      binaryData:
        channel-artifacts.zip: "{{k8s_fabric_cli_channel_artifacts}}"
  environment: "{{ kubectl_env }}"
  vars:
    channel_artifacts_configmap: "{{k8s_fabric_cli_channel_artifacts_configmap_name}}"
  when: k8s_fabric_cli_channel_artifacts

- name: Set collections facts
  set_fact:
    k8s_fabric_cli_collections_configmap_name: fabric-collections
  when: k8s_fabric_cli_collections

- name: Fabric collections configmap exists
  k8s:
    namespace: "{{k8s_fabric_cli_namespace}}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{collections_configmap}}"
      binaryData:
        collections.json: "{{k8s_fabric_cli_collections}}"
  environment: "{{ kubectl_env }}"
  vars:
    collections_configmap: "{{k8s_fabric_cli_collections_configmap_name}}"
  when: k8s_fabric_cli_collections

- name: Helm chart exists
  synchronize:
    src: fabric-cli/
    dest: "{{k8s_fabric_cli_helm_chart_path}}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes

- name: Helm Chart is installed
  kubernetes.core.helm:
    chart_ref: "{{k8s_fabric_cli_helm_chart_path}}"
    name: "fabric-cli{{item}}-{{k8s_fabric_cli_org}}"
    namespace: "{{k8s_fabric_cli_namespace}}"
    wait: true
    values:
      global:
        lutherEnv: "{{luther_env}}"
        hyperledger:
          fabricVersion: "{{k8s_fabric_version}}"
        aws:
          region: "{{k8s_fabric_cli_cert_bucket_region or shiro_phylum_s3_region}}"
          staticBucket: "{{k8s_fabric_cli_cert_bucket or shiro_phylum_s3_bucket}}"
      dlt:
        organization: "{{k8s_fabric_cli_org}}"
        mspID: "{{k8s_fabric_cli_msp}}"
        domain: "{{k8s_fabric_cli_domain_root}}"
        peerIndex: "{{item}}"
        cryptoConfigSecret: "{{crypto_config_secret}}"
        channelArtifactsConfigMap: "{{channel_artifacts_configmap}}"
        collectionsConfigMap: "{{collections_configmap}}"
      substrate:
        version: "{{k8s_fabric_cli_substrate_version or shiro_phylum_substrate_version}}"
      dockerChaincode: "{{k8s_fabric_cli_chaincode_docker}}"
      availabilityZone: "{{availability_zones[item]}}"
  environment: "{{ kubectl_env }}"
  vars:
    availability_zones: "{{k8s_fabric_cli_azs}}"
    crypto_config_secret: "{{k8s_fabric_cli_crypto_config_secret_name}}"
    channel_artifacts_configmap: "{{k8s_fabric_cli_channel_artifacts_configmap_name}}"
    collections_configmap: "{{k8s_fabric_cli_collections_configmap_name}}"
  loop: "{{range(0,k8s_fabric_cli_org_size)|list}}"
