---
# tasks file for k8s_fabric_cli

- name: K8s namespace exists
  k8s:
    name: "{{k8s_fabric_cli_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
  environment:
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"

- name: Helm chart exists
  synchronize:
    src: fabric-cli/
    dest: "{{k8s_fabric_cli_helm_chart_path}}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes

- name: Helm Chart is installed
  command:
    argv:
      - helm
      - upgrade
      - --install
      - --namespace={{k8s_fabric_cli_namespace}}
      - --set=global.lutherEnv={{luther_env}}
      - --set=global.hyperledger.fabricVersion={{k8s_fabric_version}}
      - --set=dlt.organization={{k8s_fabric_cli_org}}
      - --set=dlt.mspID={{k8s_fabric_cli_msp}}
      - --set=dlt.domain={{k8s_fabric_cli_domain_root}}
      - --set=dlt.peerIndex={{item}}
      - --set=substrate.version={{shiro_phylum_substrate_version}}
      - --set=global.aws.region={{shiro_phylum_s3_region}}
      - --set=global.aws.staticBucket={{shiro_phylum_s3_bucket}}
      - --wait
      - "fabric-cli{{item}}-{{k8s_fabric_cli_org}}"
      - "{{k8s_fabric_cli_helm_chart_path}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"
  loop: "{{range(0,k8s_fabric_cli_org_size)|list}}"
