---
# tasks file for k8s_fabric_cli

- name: K8s namespace exists
  k8s:
    name: "{{k8s_fabric_cli_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
  environment: "{{ kubectl_env }}"

- name: Helm chart exists
  synchronize:
    src: fabric-cli/
    dest: "{{k8s_fabric_cli_helm_chart_path}}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes

- name: Loop is run
  include_tasks: inner.yml
  loop: "{{range(0,k8s_fabric_cli_org_size)|list}}"
