---
# tasks file for shiro_phylum_init

- name: Phylum is initialized
  command:
    argv:
      - "{{shiro_phylum_init_script}}"
      - "{{shiro_phylum_init_substrate_version or shiro_phylum_substrate_version}}"
      - "{{shiro_phylum_init_version or shiro_phylum_version}}"
  environment: "{{ kubectl_env | combine(extra_env_vars) }}"
  vars:
    extra_env_vars:
      SHIRO_TX_COMMIT_TIMEOUT: "{{ k8s_fabric_peer_chaincode_invoke_timeout }}"
      SHIRO_TX_TIMEOUT: "{{ k8s_fabric_peer_chaincode_invoke_timeout }}"
  register: init_result
  changed_when: '"Phylum version is initialized and in service" not in init_result.stderr'
