apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-orderer.fullname" . }}
  labels:
    {{ include "fabric-orderer.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.internal.container.operationsPort | quote }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    external-dns.alpha.kubernetes.io/hostname: {{ include "fabric-orderer.self-fqdn" . }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.internal.container.operationsPort }}
      targetPort: op-http
      protocol: TCP
      name: op-http
  selector:
    app.kubernetes.io/name: {{ include "fabric-orderer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
