apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-orderer.fullname" . }}
  labels:
    {{ include "fabric-orderer.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.internal.container.operationsPort | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.internal.container.operationsPort }}
      targetPort: op-http
      protocol: TCP
      name: op-http
  selector:
    app.kubernetes.io/name: {{ include "fabric-orderer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
