---
# tasks file for k8s_fabric_orderer

- name: K8s namespace exists
  k8s:
    name: "{{k8s_fabric_orderer_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
  environment:
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"

- name: retrieve orderer PV data
  include_role:
    name: k8s_pv_data
  vars:
    org_selector: "fabric/organization={{k8s_fabric_orderer_org}}"
    k8s_pv_data_selectors: "{{k8s_fabric_orderer_pv_selectors + [org_selector]}}"

- name: Helm chart exists
  synchronize:
    src: fabric-orderer/
    dest: "{{k8s_fabric_orderer_helm_chart_path}}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes

- name: Loop is run
  include_tasks: inner.yml
  loop: "{{range(0,k8s_fabric_orderer_cluster_size)|list}}"
