---
# tasks file for k8s_fabric_orderer

- name: K8s namespace exists
  k8s:
    name: "{{k8s_fabric_orderer_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
  environment: "{{ kubectl_env }}"

- name: retrieve orderer PV data
  include_role:
    name: k8s_pv_data
  vars:
    org_selector: "fabric/organization={{k8s_fabric_orderer_org}}"
    k8s_pv_data_selectors: "{{k8s_fabric_orderer_pv_selectors + [org_selector]}}"

- name: Fabric crypto-config secrets exists
  k8s:
    namespace: "{{k8s_fabric_orderer_namespace}}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{k8s_fabric_orderer_crypto_config_secret_name}}"
      type: Opaque
      data:
        crypto-config.zip: "{{k8s_fabric_orderer_crypto_config}}"
  no_log: True
  environment: "{{ kubectl_env }}"
  when: k8s_fabric_orderer_crypto_config

- name: Fabric channel-artifacts configmap exists
  k8s:
    namespace: "{{k8s_fabric_orderer_namespace}}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{k8s_fabric_orderer_channel_artifacts_configmap_name}}"
      binaryData:
        channel-artifacts.zip: "{{k8s_fabric_orderer_channel_artifacts}}"
  environment: "{{ kubectl_env }}"
  when: k8s_fabric_orderer_channel_artifacts

- name: Helm chart exists
  synchronize:
    src: fabric-orderer/
    dest: "{{k8s_fabric_orderer_helm_chart_path}}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes

- name: Loop is run
  include_tasks: inner.yml
  loop: "{{range(0,k8s_fabric_orderer_cluster_size)|list}}"
