---
# tasks file for k8s_external_dns

- name: Add bitnami repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
  no_log: True

- name: Install public external-dns release
  kubernetes.core.helm:
    name: "{{k8s_external_dns_public_helm_release}}"
    chart_ref: "{{k8s_external_dns_chart}}"
    chart_version: "{{k8s_external_dns_chart_version}}"
    namespace: "{{k8s_external_dns_namespace}}"
    create_namespace: yes
    update_repo_cache: yes
    wait: true
    values: "{{k8s_external_dns_public_chart_values | default(default_values, true)}}"
  environment: "{{ kubectl_env }}"
  vars:
    service_account_v2:
      rbac:
        serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: "{{k8s_external_dns_public_service_account_iam_role_arn}}"
    service_account_v3:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: "{{k8s_external_dns_public_service_account_iam_role_arn}}"
    service_account: "{{service_account_v2 if k8s_external_dns_chart_version is version('3.0.0', '<') else service_account_v3}}"
    default_base_values:
      image:
        tag: "{{k8s_external_dns_image_tag}}"
      txtOwnerId: "{{luther_project_id}}-{{luther_env}}-public"
      policy: sync
      provider: aws
      aws:
        zoneType: public
      rbac:
        create: true
    default_values: "{{default_base_values | combine(service_account, recursive=True)}}"

- name: Install private external-dns release
  kubernetes.core.helm:
    name: "{{k8s_external_dns_private_helm_release}}"
    chart_ref: "{{k8s_external_dns_chart}}"
    chart_version: "{{k8s_external_dns_chart_version}}"
    namespace: "{{k8s_external_dns_namespace}}"
    create_namespace: yes
    update_repo_cache: yes
    wait: true
    values: "{{k8s_external_dns_private_chart_values | default(default_values, true)}}"
  environment: "{{ kubectl_env }}"
  vars:
    service_account_v2:
      rbac:
        serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: "{{k8s_external_dns_private_service_account_iam_role_arn}}"
    service_account_v3:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: "{{k8s_external_dns_private_service_account_iam_role_arn}}"
    service_account: "{{service_account_v2 if k8s_external_dns_chart_version is version('3.0.0', '<') else service_account_v3}}"
    default_base_values:
      image:
        tag: "{{k8s_external_dns_image_tag}}"
      txtOwnerId: "{{luther_project_id}}-{{luther_env}}-private"
      policy: sync
      provider: aws
      aws:
        zoneType: private
        # external-dns managing private hosted zones needs to filter by tag to
        # handle private zones with the same name existing in different
        # environments/vpcs.
        zoneTags:
          - Project={{luther_project_id}}
          - Environment={{luther_env}}
      rbac:
        create: true
    default_values: "{{default_base_values | combine(service_account, recursive=True)}}"

- name: Purge old values files
  file:
    path: "{{kubectl_asset_root_path}}/external-dns"
    state: absent
