---
# tasks file for k8s_external_dns

- name: Add official external-dns repository
  kubernetes.core.helm_repository:
    name: external-dns
    repo_url: https://kubernetes-sigs.github.io/external-dns/
  no_log: true

# -----------------------------
# Public external-dns
# -----------------------------
- name: Install public external-dns release (official chart)
  kubernetes.core.helm:
    name: "{{ k8s_external_dns_public_helm_release }}"
    chart_ref: "{{ k8s_external_dns_chart }}" # external-dns/external-dns
    chart_version: "{{ k8s_external_dns_chart_version }}" # e.g. 1.19.0
    namespace: "{{ k8s_external_dns_namespace }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    wait_timeout: 5m
    force: true # recreate Deployment to avoid merge issues
    atomic: true # rollback on failure
    values: "{{ k8s_external_dns_public_chart_values | default(default_values, true) }}"
  environment: "{{ kubectl_env }}"
  vars:
    service_account:
      serviceAccount:
        create: true # let the chart create the SA
        name: "{{ k8s_external_dns_public_helm_release }}"
        annotations:
          eks.amazonaws.com/role-arn: "{{ k8s_external_dns_public_service_account_iam_role_arn }}"
    default_base_values:
      txtOwnerId: "{{ luther_project_id }}-{{ luther_env }}-public"
      policy: sync
      provider: aws
      # Ensure the container port has a name so default HTTP probes work
      containerPorts:
        http: 7979
      extraArgs:
        - --aws-zone-type=public
        - --aws-api-retries=3
        - --aws-batch-change-size=1000
    default_values: "{{ default_base_values | combine(service_account, recursive=true) }}"

# -----------------------------
# Private external-dns
# -----------------------------
- name: Install private external-dns release (official chart)
  kubernetes.core.helm:
    name: "{{ k8s_external_dns_private_helm_release }}"
    chart_ref: "{{ k8s_external_dns_chart }}"
    chart_version: "{{ k8s_external_dns_chart_version }}"
    namespace: "{{ k8s_external_dns_namespace }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    wait_timeout: 5m
    force: true
    atomic: true
    values: "{{ k8s_external_dns_private_chart_values | default(default_values, true) }}"
  environment: "{{ kubectl_env }}"
  vars:
    service_account:
      serviceAccount:
        create: true
        name: "{{ k8s_external_dns_private_helm_release }}"
        annotations:
          eks.amazonaws.com/role-arn: "{{ k8s_external_dns_private_service_account_iam_role_arn }}"
    default_base_values:
      txtOwnerId: "{{ luther_project_id }}-{{ luther_env }}-private"
      policy: sync
      provider: aws
      containerPorts:
        http: 7979
      extraArgs:
        - --aws-zone-type=private
        - --aws-api-retries=3
        - --aws-batch-change-size=1000
        # Filter private zones by tags so same-name zones in other VPCs aren't touched
        - "--aws-zone-tags=Project={{ luther_project_id }},Environment={{ luther_env }}"
    default_values: "{{ default_base_values | combine(service_account, recursive=true) }}"

# Optional: clean up any old on-disk values dirs your role used before
- name: Purge old values files (legacy)
  file:
    path: "{{ kubectl_asset_root_path }}/external-dns"
    state: absent
