---
# tasks file for helm

- name: Get helm snap version
  command:
    argv:
      - snap
      - info
      - helm
  register: helm_snap_info_str
  changed_when: no

- name: Check whether upgrade is required
  set_fact:
    helm_needs_upgrade: "{{ helm_installed_channel != helm_channel }}"
    helm_installed: "{{ helm_snap_info.tracking is defined }}"
    helm_channel: "{{ helm_channel }}"
  vars:
    helm_channel: "{{ helm_version }}/stable"
    helm_snap_info: "{{ helm_snap_info_str.stdout | from_yaml }}"
    helm_installed_channel: "{{ helm_snap_info.tracking | default('') }}"

- name: Install helm
  community.general.snap:
    name: helm
    classic: yes
    state: present
    channel: "{{helm_channel}}"
  when:
    - not helm_installed

- name: Upgrade helm
  command:
    argv:
      - snap
      - refresh
      - "--channel={{helm_channel}}"
      - helm
  when:
    - helm_installed
    - helm_needs_upgrade

- when: helm_version is version('3.0', '<')
  block:
    - name: Create config directory (helm 2.x only)
      file:
        path: /root/.helm/repository
        state: directory
        recurse: yes
        mode: '0755'
    - name: Configure stable repository (helm 2.x only)
      ansible.builtin.copy:
        src: repositories.yaml
        dest: /root/.helm/repository/repositories.yaml
        owner: root
        group: root
        mode: '0644'

# legacy - remove after charts are updated
- name: Configure stable repository (helm 3.x only)
  kubernetes.core.helm_repository:
    name: stable
    repo_url: "https://charts.helm.sh/stable"
  when: helm_version is version('3.0', '>=')

- name: Install helm-diff
  kubernetes.core.helm_plugin:
    state: present
    plugin_path: https://github.com/databus23/helm-diff
    plugin_version: "{{helm_diff_plugin_version}}"
