---
- name: Check helm_version var
  fail:
    msg: "A value must be provided for helm_version"
  when: not helm_version

# TODO: remove this after applying to acre
- name: Remove deprecated snap
  community.general.snap:
    name: helm
    state: absent
  when:
    - helm_upgrade

- name: Add an apt signing key for helm
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
  when:
    - not helm_setup

- name: Adding apt repository for Helm
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm.list
  when:
    - not helm_setup

- name: Install helm binaries
  ansible.builtin.apt:
    name:
      - helm={{helm_version}}*
    state: present
    update_cache: yes

- name: Install helm-diff
  kubernetes.core.helm_plugin:
    state: present
    plugin_path: https://github.com/databus23/helm-diff
    plugin_version: "{{helm_diff_plugin_version}}"
  when:
    - not helm_setup

- name: Complete helm setup
  set_fact:
    helm_setup: yes
