---
# tasks file for k8s_coredns_config

- name: Install discovery configs
  kubernetes.core.k8s:
    namespace: kube-system
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coredns
      data:
        Corefile: "{{ lookup('template', 'corefile.yaml.j2') }}"
  environment: "{{ kubectl_env }}"
