---
# tasks file for helm_2to3

- name: Assert helm_version >= 3.0
  assert:
    that:
      - helm_version is version('3.0', '>=')

- name: Install 2to3 plugin
  command:
    argv:
      - helm
      - plugin
      - install
      - "--version={{ helm_2to3_version }}"
      - "{{ helm_2to3_url }}"
  register: helm_2to3_install_result
  failed_when:
    - helm_2to3_install_result.rc != 0
    - '"Error: plugin already exists" not in helm_2to3_install_result.stderr'

- name: Get helm 2 release info
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: kube-system
    label_selectors:
      - OWNER=TILLER
  no_log: yes
  environment: "{{ kubectl_env }}"
  register: release_info

- name: Migrate releases to helm 3
  command:
    argv:
      - helm
      - 2to3
      - convert
      - --ignore-already-migrated
      - "{{ item }}"
  environment: "{{ kubectl_env }}"
  loop: "{{ release_names }}"
  vars:
    release_versions: "{{ release_info.resources | k8s_label_to_label_map('NAME', 'str', 'VERSION') }}"
    release_names: "{{ release_versions.keys() }}"
