---
# tasks file for shiroclient_cli

- name: K8s namespace exists
  k8s:
    name: "{{shiroclient_cli_k8s_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
  environment: "{{ kubectl_env }}"

- name: Helm Chart is installed
  kubernetes.core.helm:
    chart_ref: "{{shiroclient_cli_helm_chart_path}}"
    name: "{{shiroclient_cli_helm_release}}"
    namespace: "{{shiroclient_cli_k8s_namespace}}"
    wait: true
    values:
      global:
        projectEnv: "{{luther_env}}"
      image:
        tag: "{{shiroclient_cli_substrate_version}}"
      phylum:
        version: "{{shiroclient_cli_phylum_version}}"
        name: "{{shiroclient_cli_phylum_name}}"
      runMode: cli
      substrate:
        version: "{{shiroclient_cli_substrate_version}}"
        license: "{{ shiroclient_cli_license }}"
      aws:
        region: "{{shiroclient_cli_bucket_region}}"
        phylumBucket: "{{shiroclient_cli_phylum_bucket}}"
        envBucket: "{{shiroclient_cli_env_bucket}}"
      sdk:
        bootstrapBase64: "{{shiroclient_cli_bootstrap_yaml | to_json | b64encode }}"
        phylumZipBase64: "{{shiroclient_cli_phylum_zip_base64}}"
      awsCLIVersion: "{{shiroclient_cli_aws_cli_version}}"
      dlt:
        cryptoConfigSecret: "{{shiroclient_cli_crypto_config}}"
      local: "{{mars_local | default(false)}}"
  environment: "{{ kubectl_env }}"
