---
# tasks file for helm_tiller

- name: K8s resource definitions exist
  synchronize:
    src: tiller/
    dest: "{{helm_tiller_k8s_resource_path}}"
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes
  when: helm_version is version('3.0', '<')

- name: K8s resources exist
  k8s:
    src: "{{helm_tiller_k8s_resource_path}}/{{item}}"
  with_items:
    - "{{helm_tiller_k8s_resources}}"
  environment: "{{ kubectl_env }}"
  when: helm_version is version('3.0', '<')

- name: Initialize tiller
  command:
    argv:
      - helm
      - init
      - --service-account
      - "{{helm_tiller_service_account}}"
      - --history-max={{helm_tiller_history_max}}
      - --wait
      - --upgrade
      - --tiller-connection-timeout=100
      - --override=spec.template.spec.containers[0].command={{helm_tiller_command}}
   environment: "{{ kubectl_env }}"
   when: helm_version is version('3.0', '<')
