---
# tasks file for authorized_key_sync
- name: Root path exists
  file: path={{authorized_key_sync_root_path}} state=directory recurse=yes
  tags:
    - authorized_key_sync

- name: Release root path exists
  file: path={{authorized_key_sync_release_root_path}} state=directory recurse=yes
  tags:
    - authorized_key_sync

- name: Release directory exists
  file: path={{authorized_key_sync_release_path}} state=directory
  tags:
    - authorized_key_sync

- name: Release exists
  aws_s3:
    mode: get
    region: "{{authorized_key_sync_release_s3_region}}"
    bucket: "{{authorized_key_sync_release_s3_bucket}}"
    object: "{{authorized_key_sync_release_s3_key}}"
    dest: "{{authorized_key_sync_release_archive_path}}"
    ignore_nonexistent_bucket: yes
    aws_access_key: "{{kubectl_aws_access_key_id}}"
    aws_secret_key: "{{kubectl_aws_secret_access_key}}"
    security_token: "{{kubectl_aws_session_token}}"
  tags:
    - authorized_key_sync

- name: Release has been unarchived
  unarchive: dest={{authorized_key_sync_release_path}} src={{authorized_key_sync_release_archive_path}} remote_src=yes creates={{authorized_key_sync_release_executable_path}}
  tags:
    - authorized_key_sync

- name: Executable symlink directory exists
  file: path={{authorized_key_sync_executable_path|dirname}} state=directory
  tags:
    - authorized_key_sync

- name: Executable symlink exists
  file: path={{authorized_key_sync_executable_path}} state=link src={{authorized_key_sync_release_executable_path}}
  tags:
    - authorized_key_sync
  notify:
    - authorized_key_sync restart

- name: Config directory exists
  file: path={{authorized_key_sync_config_path|dirname}} state=directory
  tags:
    - authorized_key_sync

- name: Config exists
  template: dest={{authorized_key_sync_config_path}} src=config.yaml.j2
  tags:
    - authorized_key_sync
  notify:
    - authorized_key_sync restart

- name: Systemd unit file exists
  template: dest={{authorized_key_sync_systemd_unit_path}} src=authorized_key_sync.service.j2
  tags:
    - authorized_key_sync
  notify:
    - authorized_key_sync enable
    - authorized_key_sync restart

- name: Service is started
  command: /bin/true
  tags:
    - authorized_key_sync
  notify:
    - authorized_key_sync enable
    - authorized_key_sync start

- name: Process handlers
  meta: flush_handlers
  tags:
    - authorized_key_sync
