{{- if .Values.rbac.create }}

# Grant connectorhub SA the ability to manage pods & subresources
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "connectorhub.fullname" . }}-launcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "connectorhub.labels" . | nindent 4 }}
rules:
  # Pods: create, delete, get/list/watch (for status)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","watch"]
  # Pod subresources: exec, logs, attach
- apiGroups: [""]
  resources: ["pods/exec","pods/log","pods/attach"]
  verbs: ["create","get"]
  # Secrets: upsert your in-memory files
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","watch","create","update","patch","delete"]

---
# Bind that Role to your ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "connectorhub.fullname" . }}-launcher-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "connectorhub.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "connectorhub.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "connectorhub.fullname" . }}-launcher
  apiGroup: rbac.authorization.k8s.io

{{- end }}
