apiVersion: v1
kind: Service
metadata:
  name: {{ include "connectorhub.fullname" . }}
  labels:
    {{- include "connectorhub.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/v1/ch/health_check"
    alb.ingress.kubernetes.io/healthcheck-port: "traffic-port"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.main.port }}
      targetPort: {{ .Values.service.main.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.service.test.enabled }}
    - port: {{ .Values.service.test.port }}
      targetPort: {{ .Values.service.test.targetPort }}
      protocol: TCP
      name: test-api
    {{- end }}
  selector:
    {{- include "connectorhub.labels" . | nindent 4 }}
