{{- if eq .Values.runMode "gateway"}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shiroclient.fullname" . }}
  labels:
    {{- include "shiroclient.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.metrics | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "shiroclient.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
