---
# tasks file for k8s_fabric_channel

- name: Create channel
  command:
    argv:
      - "{{k8s_fabric_channel_create_script_path}}"
    chdir: "{{k8s_fabric_scripts_workdir}}"
  vars:
    extra_env_vars:
      FABRIC_DOMAIN: "{{k8s_fabric_channel_domain_root}}"
  environment: "{{ kubectl_env | combine(extra_env_vars) }}"

- name: Join channel
  command:
    argv:
      - "{{k8s_fabric_channel_sync_script_path}}"
      - "{{item.name}}"
    chdir: "{{k8s_fabric_scripts_workdir}}"
  vars:
    extra_env_vars:
      FABRIC_DOMAIN: "{{k8s_fabric_channel_domain_root}}"
  environment: "{{ kubectl_env | combine(extra_env_vars) }}"
  loop: "{{k8s_fabric_channel_orgs}}"

- name: Update Anchor peers
  command:
    argv:
      - "{{k8s_fabric_channel_anchor_script_path}}"
      - "{{item.name}}"
      - "{{item.msp}}"
    chdir: "{{k8s_fabric_scripts_workdir}}"
  vars:
    extra_env_vars:
      FABRIC_DOMAIN: "{{k8s_fabric_channel_domain_root}}"
  environment: "{{ kubectl_env | combine(extra_env_vars) }}"
  loop: "{{k8s_fabric_channel_orgs}}"
