# Default values for fabric-cli.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  lutherEnv: dev
  partOf: fabric
  hyperledger:
    fabricVersion: 1.4.2
  aws:
    region: ""
    staticBucket: ""

replicaCount: 1

# coreConfigMap is the name of a ConfigMap resource that contains a core.yaml
# configuration file.
coreConfigMap: fabric-peer-config

dlt:
  component: bccli
  organization: org1
  mspID: Org1MSP
  peerIndex: 0
  domain: luther.systems
  # IMPORTANT: all 3 of these must be specified together!
  cryptoConfigSecret: ""
  channelArtifactsConfigMap: ""
  collectionsConfigMap: ""

image:
  repository: hyperledger/fabric-tools
  pullPolicy: IfNotPresent

substrate:
  version: 2.96.0
  s3:
    region: eu-west-2
    bucket: luther-common-ln-common-external-s3-44lp

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

internal:
  container:
    servicePort: 7053
    chaincodePort: 7052
    gossipPort: 7051
    operationsPort: 9443

service:
  type: ClusterIP
  port: 7053

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

availabilityZone: ""

tolerations: []

affinity: {}

awsCLIVersion: latest

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  # Automount API credentials for a Service Account.
  automountServiceAccountToken: true
  # List of image pull secrets to add to the Service Account.
  imagePullSecrets:
    # - name: docker
