{{- if .Values.proxy.authToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcpinspector.fullname" . }}-secrets
type: Opaque
stringData:
  proxy_token: {{ .Values.proxy.authToken | quote }}
{{- end }}
