dependencies:
  - name: prometheus
    version: ~9.3.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: grafana
    version: ~4.0.3
    repository: https://kubernetes-charts.storage.googleapis.com/

