---
# tasks file for k8s_fabric_peer loop

- name: Helm Chart is installed
  command:
    argv:
      - helm
      - upgrade
      - --install
      - --namespace={{k8s_fabric_peer_namespace}}
      - --set=global.lutherEnv={{luther_env}}
      - --set=global.hyperledger.fabricVersion={{k8s_fabric_version}}
      - --set=dlt.organization={{k8s_fabric_peer_org}}
      - --set=dlt.mspID={{k8s_fabric_peer_msp}}
      - --set=dlt.domain={{k8s_fabric_peer_domain_root}}
      - --set=dlt.peerIndex={{item}}
      - --set=substrate.version={{shiro_phylum_substrate_version}}
      - --set=global.aws.region={{shiro_phylum_s3_region}}
      - --set=global.aws.staticBucket={{shiro_phylum_s3_bucket}}
      - --set=image.repository={{k8s_fabric_peer_image_repository}}
      - --set=startService={{k8s_fabric_peer_start_service}}
      - --set=internal.container.invokeTimeout={{k8s_fabric_peer_chaincode_invoke_timeout}}
      - --set=persistentVolume.storageSize={{k8s_fabric_peer_storage_size}}
      - --wait
      - "fabric-peer{{item}}-{{k8s_fabric_peer_org}}"
      - "{{k8s_fabric_peer_helm_chart_path}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"

- name: Upgrade pauser has run
  when: is_fabric_upgrade | bool
  command:
    argv:
    - ./upgrade-pauser.sh
  args:
    chdir: "{{k8s_fabric_channel_workdir}}/scripts"
  environment:
    PAUSING_AT: "peer"
    WHICH: "{{item}}"
    CHANNEL: "luther"
    ORDERERC: "{{k8s_fabric_orderer_cluster_size}}"
    PEER_ORG: "{{k8s_fabric_peer_org}}"
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"
