---
# tasks file for k8s_fabric_peer

- name: K8s namespace exists
  k8s:
    name: "{{k8s_fabric_peer_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
  environment:
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"

- name: ConfigMap directory exists
  file:
    path: "{{k8s_fabric_peer_configmap_path | dirname}}"
    state: directory

- name: ConfigMap is rendered
  template:
    src: configmap.yaml.j2
    dest: "{{k8s_fabric_peer_configmap_path}}"

- name: K8s ConfigMap exists
  k8s:
    src: "{{k8s_fabric_peer_configmap_path}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"

- name: Helm chart exists
  synchronize:
    src: fabric-peer/
    dest: "{{k8s_fabric_peer_helm_chart_path}}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes

- name: Helm Chart is installed
  command:
    argv:
      - helm
      - upgrade
      - --install
      - --namespace={{k8s_fabric_peer_namespace}}
      - --set=global.lutherEnv={{luther_env}}
      - --set=dlt.organization={{k8s_fabric_peer_org}}
      - --set=dlt.mspID={{k8s_fabric_peer_msp}}
      - --set=dlt.domain={{k8s_fabric_peer_domain_root}}
      - --set=dlt.peerIndex={{item}}
      - --set=substrate.version={{shiro_phylum_substrate_version}}
      - --set=global.aws.region={{shiro_phylum_s3_region}}
      - --set=global.aws.staticBucket={{shiro_phylum_s3_bucket}}
      - --set=image.repository={{k8s_fabric_peer_image_repository}}
      - --set=startService={{k8s_fabric_peer_start_service}}
      - --set=internal.container.invokeTimeout={{k8s_fabric_peer_chaincode_invoke_timeout}}
      - --wait
      - "fabric-peer{{item}}-{{k8s_fabric_peer_org}}"
      - "{{k8s_fabric_peer_helm_chart_path}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"
  loop: "{{range(0,k8s_fabric_peer_org_size)|list}}"
