---
# tasks file for k8s_fabric_chaincode loop

- name: Helm Chart is installed
  kubernetes.core.helm:
    chart_ref: "{{k8s_fabric_chaincode_helm_chart_path}}"
    name: "substrate-{{ cc_dash_ver }}-peer{{ item.1 }}"
    namespace: "fabric-{{ item.0 }}"
    wait: true
    values:
      image:
        version: "{{k8s_fabric_chaincode_version}}"
      service:
        name: "substrate-{{ cc_dash_ver }}-peer{{ item.1 }}"
      ccid: "{{install_result.results[index].stdout}}"
      dlt:
        organization: "{{item.0 }}"
        peerIndex: "{{item.1}}"
      availabilityZone: "{{availability_zones[item.1]}}"
      env:
        CHAINCODE_LOG_LEVEL: "{{k8s_fabric_chaincode_loglevel}}"
  when: k8s_fabric_chaincode_external and not committed
  tags:
  - prepare_chaincode_upgrade
  environment: "{{ kubectl_env }}"
  vars:
    availability_zones: "{{k8s_fabric_chaincode_azs}}"
