---
# tasks file for k8s_fabric_scripts

- name: Scripts directory exists
  file:
    path: "{{k8s_fabric_scripts_dir}}"
    state: directory
    recurse: yes
  tags: fabric_scripts
  when: not mars_local | default(false)

- name: Scripts are uploaded
  synchronize:
    src: scripts/
    dest: "{{k8s_fabric_scripts_dir}}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes
  tags: fabric_scripts
  when: not mars_local | default(false)
