apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-ca.fullname" . }}
  labels:
{{ include "fabric-ca.labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.internal.container.operationsPort | quote }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "fabric-ca.service-fqdn" . }}
    {{- if eq .Values.service.type "LoadBalancer" }}
    {{- if .Values.service.useNLB }}
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    {{- else }}
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: {{ .Values.service.idleTimeout | quote }}
    {{- end }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Project={{ .Values.global.lutherProjectID }},Environment={{ .Values.global.lutherEnv }},Organization={{ .Values.dlt.organization }},Component={{.Values.dlt.component}},Resource=elb
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.internal.container.operationsPort }}
      targetPort: http-op
      protocol: TCP
      name: http-op
  selector:
    app.kubernetes.io/name: {{ include "fabric-ca.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
