---
# tasks file for eks_cluster_init

- name: Annotate non-default StorageClass objects
  kubernetes.core.k8s:
    kind: StorageClass
    name: "{{item}}"
    resource_definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
  loop: "{{eks_cluster_init_nondefault_storageclasses}}"
  environment: "{{ kubectl_env }}"

- name: Enable volume resizing on StorageClass objects
  kubernetes.core.k8s:
    kind: StorageClass
    name: "{{item}}"
    resource_definition:
      allowVolumeExpansion: true
  loop: "{{eks_cluster_init_enable_resize_storageclasses}}"
  environment: "{{ kubectl_env }}"
