---
# tasks file for eks_cluster_init

- name: Annotate non-default StorageClass objects
  k8s:
    kind: StorageClass
    name: "{{item}}"
    resource_definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
  loop: "{{eks_cluster_init_nondefault_storageclasses}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{kubectl_aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{kubectl_aws_secret_access_key}}"
    AWS_SESSION_TOKEN: "{{kubectl_aws_session_token}}"
    KUBECONFIG: "{{kubectl_config_path}}"
