---
# tasks file for eks_cluster_init

- name: Enable IAM admin role access
  kubernetes.core.k8s:
    kind: ConfigMap
    name: aws-auth
    namespace: kube-system
    definition:
      data:
        mapRoles: "{{ map_roles | to_nice_yaml(indent=2) }}"
  vars:
    map_roles:
      - rolearn: "{{ eks_cluster_init_eks_worker_iam_role_arn }}"
        username: !unsafe system:node:{{EC2PrivateDNSName}}
        groups:
          - system:bootstrappers
          - system:nodes
      - rolearn: "{{ eks_cluster_init_k8s_admin_role_arn }}"
        username: luther:admin
        groups:
          - system:masters
  environment: "{{ kubectl_env }}"
  when:
    - eks_cluster_init_configure_aws_auth
    - eks_cluster_init_eks_worker_iam_role_arn is defined
    - eks_cluster_init_k8s_admin_role_arn is defined

- name: Get all StorageClasses
  kubernetes.core.k8s_info:
    kind: StorageClass
    api_version: storage.k8s.io/v1
  register: storage_classes
  environment: "{{ kubectl_env }}"

- name: Set current default StorageClass variable
  set_fact:
    current_default_sc: "{{ item.metadata.name }}"
  loop: "{{ storage_classes.resources }}"
  when: item.metadata.annotations['storageclass.kubernetes.io/is-default-class'] | default('false') == 'true'
  no_log: true

- name: Enable volume resizing on StorageClass objects if not already enabled
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: "{{ item.metadata.name }}"
    definition:
      allowVolumeExpansion: true
  loop: "{{ storage_classes.resources }}"
  when: item.allowVolumeExpansion is not defined or item.allowVolumeExpansion == false
  environment: "{{ kubectl_env }}"

- name: Create encrypted StorageClasses
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: "{{ item }}-encrypted"
    definition:
      provisioner: kubernetes.io/aws-ebs
      parameters:
        type: "{{ item }}"
        fsType: ext4
        encrypted: "true"
        kmsKeyId: "{{ eks_cluster_init_storage_kms_key_id }}"
      reclaimPolicy: "{{ eks_cluster_init_volume_reclaim_policy }}"
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
  loop: "{{ eks_cluster_init_available_encrypted_storage_types }}"
  when: eks_cluster_init_storage_kms_key_id is defined
  environment: "{{ kubectl_env }}"

- name: Remove default annotation from current default StorageClass
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: "{{ current_default_sc }}"
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
  when:
    - current_default_sc is defined
    - current_default_sc | length > 0
    - current_default_sc != eks_cluster_init_default_storageclass
  environment: "{{ kubectl_env }}"

- name: Set specific StorageClass as default if not already set
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: "{{ eks_cluster_init_default_storageclass }}"
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  when:
    - eks_cluster_init_default_storageclass is defined
    - eks_cluster_init_default_storageclass | length > 0
    - current_default_sc != eks_cluster_init_default_storageclass
  environment: "{{ kubectl_env }}"
