apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-peer.fullname" . }}
  labels:
    {{- include "fabric-peer.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.internal.container.operationsPort | quote }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    external-dns.alpha.kubernetes.io/hostname: {{ include "fabric-peer.self-fqdn" . }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.internal.container.gossipPort }}
      targetPort: grpc-gossip
      protocol: TCP
      name: grpc-gossip
    - port: {{ .Values.service.port }}
      targetPort: grpc-svc
      protocol: TCP
      name: grpc-svc
    - port: {{ .Values.internal.container.operationsPort }}
      targetPort: http-op
      protocol: TCP
      name: http-op
  selector:
    app.kubernetes.io/name: {{ include "fabric-peer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
