---
# tasks file for k8s_monitoring

- name: Monitoring namespace exists
  k8s:
    name: "{{k8s_monitoring_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
  environment: "{{ kubectl_env }}"

- name: Alertmanager config exists
  k8s:
    namespace: "{{k8s_monitoring_namespace}}"
    name: "{{prometheus_alertmanager_configmap_fullname}}"
    api_version: v1
    kind: ConfigMap
    resource_definition:
      data: "{{prometheus_alertmanager_configmap_data}}"
    state: present
  environment: "{{ kubectl_env }}"

- name: Grafana admin credentials exist
  k8s:
    namespace: "{{k8s_monitoring_namespace}}"
    name: "{{grafana_credentials_secret_name}}"
    api_version: v1
    kind: Secret
    resource_definition:
      data:
        admin-user: "{{grafana_admin_user | b64encode}}"
        admin-password: "{{grafana_admin_password | b64encode}}"
    state: present
  environment: "{{ kubectl_env }}"

- name: Google OAuth client credentials exist
  k8s:
    namespace: "{{k8s_monitoring_namespace}}"
    name: "{{grafana_env_secret_name}}"
    api_version: v1
    kind: Secret
    resource_definition:
      data:
        GF_AUTH_GOOGLE_CLIENT_ID: "{{grafana_google_client_id | b64encode}}"
        GF_AUTH_GOOGLE_CLIENT_SECRET: "{{grafana_google_client_secret | b64encode}}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{grafana_custom_oauth_config.client_id | default('') | b64encode}}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{grafana_custom_oauth_config.client_secret | default ('') | b64encode}}"
    state: present
  environment: "{{ kubectl_env }}"

- name: Grafana dashboards configmap directory exists
  file:
    path: "{{grafana_dashboard_configmap_path | dirname}}"
    state: directory
    recurse: true

- name: Grafana dashboards configmap definition exists
  template:
    src: dashboard_configmap.yaml.j2
    dest: "{{grafana_dashboard_configmap_path}}"

- name: Grafana dashboards configmap exists
  k8s:
    src: "{{grafana_dashboard_configmap_path}}"
  environment: "{{ kubectl_env }}"

- name: Chart values directory exists
  file:
    path: "{{k8s_monitoring_chart_values_path | dirname}}"
    state: directory
    recurse: true

- name: Chart values exist
  template:
    src: values.yaml.j2
    dest: "{{k8s_monitoring_chart_values_path}}"

- name: Helm chart exists
  synchronize:
    src: monitoring-umbrella/
    dest: "{{k8s_monitoring_chart_path}}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    use_ssh_args: yes

- name: Helm chart is installed
  # TODO: use k8s core
  command:
    argv:
      - helm
      - upgrade
      - --install
      - --wait
      - --values={{k8s_monitoring_chart_values_path}}
      - --namespace={{k8s_monitoring_namespace}}
      - --set
      - "prometheus.extraScrapeConfigs={{lookup('template', 'extra_scrape_configs.yaml.j2')}}"
      - "{{k8s_monitoring_helm_release}}"
      - "{{k8s_monitoring_chart_path}}"
  environment: "{{ kubectl_env }}"
