---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "pvc.labels" . | nindent 4 }}
  {{- if .Values.volumeTypeOverride }}
  annotations:
    ebs.csi.aws.com/volumeType: {{ .Values.volumeTypeOverride }}
  {{- end }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
