name: Build Release and Push
on:
  push:
    tags:
      - "*"
env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
jobs:
  build-push:
    name: ${{ matrix.image }} - ${{ matrix.arch }} docker build
    runs-on: ${{ fromJSON('{"arm64":"2vcpu-ubuntu-2204-arm","amd64":"ubuntu-20.04"}')[matrix.arch] }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        image:
          - mars
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # include tags for VERSION detection
      - name: Build container
        uses: ./.github/actions/build-docker-images
        with:
          arch: ${{ matrix.arch }}
          image: .
          git_tag: $GITHUB_REF_NAME
  push-manifests:
    runs-on: ubuntu-20.04
    needs:
      - build-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure DockerHub
        uses: ./.github/actions/configure-dockerhub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create and push manifest for multiarch
        run: make push-manifests GIT_TAG=$GITHUB_REF_NAME
